buildscript {
    ext.kotlin_version = '1.8.0'  // Use a compatible version
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    //ext.kotlin_version = '1.8.0'  // Use a compatible version

    // Force all plugins to use the same Kotlin version
    if (project.hasProperty('android')) {
        project.android {
            kotlinOptions {
                jvmTarget = '1.8'
            }
        }
    }

    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion kotlin_version
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
